## SPDX-License-Identifier: MIT
## Copyright 2023 BooleWorks GmbH

# the site
site_name: BooleRules
site_url: https://www.boolerules.com
site_description: The Boolean Rule Engine for Everyone
site_author: BooleWorks GmbH

# the repository
# repo_name: logic-ng/LogicNG
# repo_url: https://github.com/logic-ng/LogicNG
# edit_uri: ""

# Copyright
copyright: Copyright &copy; BooleWorks GmbH

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.annotate
    - navigation.tabs
    - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - media: "(prefers-color-scheme)"
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/booleworks/
      name: BooleWorks on GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/booleworks
      name: BooleWorks on LinkedIn

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.tilde
  - tables
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Overview: index.md
  - The Rule Language:
      - language/index.md
      - Features: language/features.md
      - Rules: language/rules.md
      - Modules: language/modules.md
      - Constraints: language/constraints.md
  - Legal:
      - Privacy Policy: legal/privacy.md
      - Corporate Information: legal/corporate.md
